
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_Banking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8081
